#数据库
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/test
     username: root
     password: 123456
     driver-class-name: com.mysql.jdbc.Driver


     
#自定义属性配置 
my:
  name: nxd
    
heluo:
  #userId配置
  userid:
    #userId开启
    authEnable: true
    #放行路径
    excludePath: 
    

#mybatis驼峰转换 
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
